name: CI
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm ci
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Affected Package
        id: affected_package
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: "master"
      - run: |
          npx nx affected --target=build --parallel=1 --args="--projectVersion={project.version} --nodeImage={project.nodeImage} --projectSourceDir={project.sourceRoot}"
      - name: Build and push Docker Image
        if: ${{ env.docker_file != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.docker_context }}
          file: ${{ env.docker_file }}
          push: true
          tags: ${{ env.docker_tag }}
